# docker/docker-compose.dev.yml
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev  # Будет специальный Dockerfile для разработки
    ports:
      - "8081:8081"
      - "9000:9000"  # Порт для air (если нужно)
    env_file:
      - .env.test
    volumes:
      - ../:/app  # Монтируем весь код
      - ../tmp:/app/tmp  # Для бинарников air
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: air -c .air.toml  # Запускаем air вместо обычного бинарника

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local