version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "9000:9000"  
    env_file:
      - .env
    volumes:
      - ../:/app  
      - ../tmp:/app/tmp
      - ../migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: air -c .air.toml

  postgres:
    image: postgres:13
    env_file:
     - .env
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local