version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ../migrations:/app/migrations 
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local