# docker/Dockerfile.dev
FROM golang:1.24-alpine

WORKDIR /app

# Устанавливаем зависимости и air
RUN apk add --no-cache git ca-certificates tzdata curl

# Устанавливаем air
RUN go install github.com/air-verse/air@latest

# Копируем зависимости для кеширования
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Создаем директорию для бинарников
RUN mkdir -p tmp

EXPOSE 8081
# CMD будет переопределен в docker-compose
CMD ["./tmp/main"]